load("@rules_python//python:defs.bzl", "py_library")
load("@webservice//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "webservice",
    srcs = ["data.py"],
)
